version: "3.9"

services:
  postgres:
    container_name: realtor_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - angular-realtor-db:/var/lib/postgresql/data
  # api:
  #   container_name: realtor_api
  #   build:
  #     context: /backend
  #     dockerfile: Dockerfile
  #   environment:
  #     DB_SCHEMA: postgres
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_HOST: postgres
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  # api:
  #   container_name: realtor_api
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  # - redis
  # - rabbitmq

  # frontend:
  #   container_name: realtor_frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api

  # redis:
  #   container_name: realtor_redis
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"

  # rabbitmq:
  #   container_name: realtor_rabbitmq
  #   image: "rabbitmq:3-management"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
volumes:
  angular-realtor-db:

networks:
  default:
    name: realtor_network
